//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpyCamcorder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpyCamcorder.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spy Camcorder.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KLBCreations.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to delete all of your videos?  Warning:  once deleted, they can not be recovered!.
        /// </summary>
        public static string DeleteAllVideos {
            get {
                return ResourceManager.GetString("DeleteAllVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Videos.
        /// </summary>
        public static string DeleteAllVideos1 {
            get {
                return ResourceManager.GetString("DeleteAllVideos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        public static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the settings screen to view the settings..
        /// </summary>
        public static string Instruction1 {
            get {
                return ResourceManager.GetString("Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select either the front or rear camera.  You may also turn the auto lock screen off here..
        /// </summary>
        public static string Instruction2 {
            get {
                return ResourceManager.GetString("Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the light is green, the application is ready to record a video.  To begin recording, tap the refresh button..
        /// </summary>
        public static string Instruction3 {
            get {
                return ResourceManager.GetString("Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the refresh button is yellow, the video is beginning to record..
        /// </summary>
        public static string Instruction4 {
            get {
                return ResourceManager.GetString("Instruction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the video is recording, the button is red.  To stop the recording, tap the red button..
        /// </summary>
        public static string Instruction5 {
            get {
                return ResourceManager.GetString("Instruction5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To review your videos, tap the videos button..
        /// </summary>
        public static string Instruction6 {
            get {
                return ResourceManager.GetString("Instruction6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press play to play the video, and delete to delete the video..
        /// </summary>
        public static string Instruction7 {
            get {
                return ResourceManager.GetString("Instruction7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From here, you can stop, replay, pause, and upload the video to skydrive.  Please note you must be connected to wifi to upload a video..
        /// </summary>
        public static string Instruction8 {
            get {
                return ResourceManager.GetString("Instruction8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete all of your videos from your phone, tap the delete all videos button..
        /// </summary>
        public static string Instruction9 {
            get {
                return ResourceManager.GetString("Instruction9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Timeout Disabled.
        /// </summary>
        public static string LockDisabled {
            get {
                return ResourceManager.GetString("LockDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Timeout Enabled.
        /// </summary>
        public static string LockEnabled {
            get {
                return ResourceManager.GetString("LockEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Apps from KLBCREATIONS.
        /// </summary>
        public static string MoreAps {
            get {
                return ResourceManager.GetString("MoreAps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyDrive.
        /// </summary>
        public static string SkyDrive {
            get {
                return ResourceManager.GetString("SkyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1:.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2:.
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3:.
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4:.
        /// </summary>
        public static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5:.
        /// </summary>
        public static string Step5 {
            get {
                return ResourceManager.GetString("Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 6:.
        /// </summary>
        public static string Step6 {
            get {
                return ResourceManager.GetString("Step6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 7:.
        /// </summary>
        public static string Step7 {
            get {
                return ResourceManager.GetString("Step7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 8:.
        /// </summary>
        public static string Step8 {
            get {
                return ResourceManager.GetString("Step8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 9:.
        /// </summary>
        public static string Step9 {
            get {
                return ResourceManager.GetString("Step9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are recording!  Stop recording to view your videos..
        /// </summary>
        public static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KlbCreations01@yahoo.com.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test1 {
            get {
                return ResourceManager.GetString("Test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial has expired.  Please support the developers, and purchase this application!.
        /// </summary>
        public static string TrialExpired {
            get {
                return ResourceManager.GetString("TrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have .
        /// </summary>
        public static string TrialLeft1 {
            get {
                return ResourceManager.GetString("TrialLeft1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days remaining in your trial.  To Extend your trial from 3 days to 10 Days, Rate this app 5 stars, and leave a positive comment..
        /// </summary>
        public static string TrialLeft2 {
            get {
                return ResourceManager.GetString("TrialLeft2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Trial?.
        /// </summary>
        public static string TrialLeft3 {
            get {
                return ResourceManager.GetString("TrialLeft3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days remaining in your trial.  Do you wish to purchase the application?.
        /// </summary>
        public static string TrialLeft4 {
            get {
                return ResourceManager.GetString("TrialLeft4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase?.
        /// </summary>
        public static string TrialLeft5 {
            get {
                return ResourceManager.GetString("TrialLeft5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.
        /// </summary>
        public static string VersionString {
            get {
                return ResourceManager.GetString("VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Free Today!!
        ///
        ///This application is allows you to take discreet videos while browsing the web.
        ///
        ///A user can:
        ///
        ///* Record a Video
        ///* Review the Video
        ///* Upload the Video to SkyDrive when using Wifi
        ///* Delete all videos
        ///* Toggle Front Camera or Rear Camera
        ///
        ///KLBCreations is NOT responsible for mis-use of this application..
        /// </summary>
        public static string zDescription {
            get {
                return ResourceManager.GetString("zDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camcorder.
        /// </summary>
        public static string zWord1 {
            get {
                return ResourceManager.GetString("zWord1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string zWord2 {
            get {
                return ResourceManager.GetString("zWord2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spy Camcorder.
        /// </summary>
        public static string zWord3 {
            get {
                return ResourceManager.GetString("zWord3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpyCam.
        /// </summary>
        public static string zWord4 {
            get {
                return ResourceManager.GetString("zWord4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stealth Video.
        /// </summary>
        public static string zWord5 {
            get {
                return ResourceManager.GetString("zWord5", resourceCulture);
            }
        }
    }
}
